version: '3'

services:
  climbunity_app:
    container_name: climbunity_app
    build: .
    ports:
      - "5002:5002"
    environment:
      - SECRET_KEY=password
      - DATABASE_URL=postgresql://postgres:postgres@postgres_db:5432/postgres
    depends_on:
      postgres_db:
        condition: service_healthy
        
  postgres_db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: {}
  
  